version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    env_file: 
      - .env
    environment:
      - PORT=${PORT_AUTH}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "${PORT_AUTH}:${PORT_AUTH}"
    depends_on:
      - postgres

  main-service:
    build: ./backend/main-service
    container_name: main-service
    env_file: 
      - .env
    environment:
      - PORT=${PORT_MAIN}
      - DB_HOST=postgres  
      - DB_PORT=5432      
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "${PORT_MAIN}:${PORT_MAIN}"
    depends_on:
      - postgres
      - auth-service

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${PORT_FRONTEND}:80"
    depends_on:
      - main-service
      - auth-service

volumes:
  postgres_data: