services:
  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    ports:
      - "${PORT_AUTH}:${PORT_AUTH}"
    env_file:
      - .env
    environment:
      - PORT=${PORT_AUTH}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - postgres

  main-service:
    build: ./backend/main-service
    container_name: main-service
    ports:
      - "${PORT_MAIN}:${PORT_MAIN}"
    env_file:
      - .env
    environment:
      - PORT=${PORT_MAIN}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - postgres
      - auth-service

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${PORT_FRONTEND}:80"
    env_file:
      - .env
    depends_on:
      - main-service
      - auth-service

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: