# Start from official Go image
FROM golang:1.24-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV GIN_MODE=release

RUN go build -o main-service ./cmd/main.go

CMD ["./main-service"]
